// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLssNiIi9c3qUx7B_WgeyOMdZEYnokwno',
    appId: '1:381580421966:web:323b5128bd9d0dac7ccc1f',
    messagingSenderId: '381580421966',
    projectId: 'dating-app-aa0d5',
    authDomain: 'dating-app-aa0d5.firebaseapp.com',
    storageBucket: 'dating-app-aa0d5.firebasestorage.app',
    measurementId: 'G-WV237VRNJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBo__7-8foaZ83ON5iNvaf6J-sZmzgmQCU',
    appId: '1:381580421966:android:3aab93acd91ea9427ccc1f',
    messagingSenderId: '381580421966',
    projectId: 'dating-app-aa0d5',
    storageBucket: 'dating-app-aa0d5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkqDAkSEzcNf6zr-nbrRcLazb6qBB-zNo',
    appId: '1:381580421966:ios:199ac077a0a585a47ccc1f',
    messagingSenderId: '381580421966',
    projectId: 'dating-app-aa0d5',
    storageBucket: 'dating-app-aa0d5.firebasestorage.app',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkqDAkSEzcNf6zr-nbrRcLazb6qBB-zNo',
    appId: '1:381580421966:ios:199ac077a0a585a47ccc1f',
    messagingSenderId: '381580421966',
    projectId: 'dating-app-aa0d5',
    storageBucket: 'dating-app-aa0d5.firebasestorage.app',
    iosBundleId: 'com.example.dating',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLssNiIi9c3qUx7B_WgeyOMdZEYnokwno',
    appId: '1:381580421966:web:5c002feb873a77d67ccc1f',
    messagingSenderId: '381580421966',
    projectId: 'dating-app-aa0d5',
    authDomain: 'dating-app-aa0d5.firebaseapp.com',
    storageBucket: 'dating-app-aa0d5.firebasestorage.app',
    measurementId: 'G-46K97GZ7B6',
  );
}
